#To Change from /camel to /books in url
camel:
  springboot:
    name: BooksAPI
  servlet:
    mapping:
      context-path: /*
  rest:
    context-path: /
    
server:
  port: 8080
  
booksDB:
  host: ${BACKEND_URL}